POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "All About Fish",
    "author": "Gerhard Manning",
    "url": "http://kitchentrends.com/allaboutfish",
    "likes": 882
}