POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Chinese Cuisine",
    "author": "Lizzy Smith",
    "url": "http://foodblogs.com/lizzyschinesecuisine",
    "likes": 572
}