POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "url": "http://foodblogs.com/lizzyschinesecuisine",
    "title": "Chinese Cuisine",
    "author": "Lizzy Smith",
    "userId": "6238741602cdb0aed09dc6cb",
    "likes": 572
}